#!/usr/bin/env bash
# RAKSHAK - one command startup (Linux / macOS).
# Mirrors scripts/start.ps1: same modes, same detection, same env files.
#   ./scripts/start.sh [-m docker|local] [--host-ip x.x.x.x] [--rebuild]
#                       [--no-mobile] [--reset] [--force-seed]
set -uo pipefail

# --------------------------------------------------------------------------- #
# Arguments
# --------------------------------------------------------------------------- #
MODE="auto"
HOST_IP=""
REBUILD=0
NO_MOBILE=0
RESET=0
FORCE_SEED=0
SKIP_FIREWALL=0
PHONE_STATE="not-checked"   # authorized | unauthorized | none | no-adb | not-checked

while [ $# -gt 0 ]; do
  case "$1" in
    -m|--mode)        MODE="${2:-auto}"; shift 2 ;;
    -m=*|--mode=*)     MODE="${1#*=}"; shift ;;
    --host-ip)        HOST_IP="${2:-}"; shift 2 ;;
    --host-ip=*)      HOST_IP="${1#*=}"; shift ;;
    --rebuild)        REBUILD=1; shift ;;
    --no-mobile)      NO_MOBILE=1; shift ;;
    --reset)          RESET=1; shift ;;
    --force-seed)     FORCE_SEED=1; shift ;;
    --skip-firewall)  SKIP_FIREWALL=1; shift ;;
    -h|--help)
      sed -n '2,9p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_DIR="$REPO_ROOT/.rakshak"
LOG_DIR="$REPO_ROOT/logs"
ENV_PATH="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"
PIDS_PATH="$STATE_DIR/pids.json"
HASHES_PATH="$STATE_DIR/hashes.json"
# Records the detected network so the NEXT run can tell whether it moved.
STATE_PATH="$STATE_DIR/state.json"
SEED_MARKER="$STATE_DIR/seed.done"

BACKEND_DIR="$REPO_ROOT/backend"
CITIZEN_DIR="$REPO_ROOT/citizen_web"
POLICE_DIR="$REPO_ROOT/police_dashboard"
MOBILE_DIR="$REPO_ROOT/mobile_app"
VENV_DIR="$REPO_ROOT/.venv"

PORT_BACKEND=8000
PORT_CITIZEN=5173
PORT_POLICE=5174
PORT_EXPO=8081

EFFECTIVE_MODE="local"
LAN_IP=""
FRESH=1

# --------------------------------------------------------------------------- #
# Output helpers
# --------------------------------------------------------------------------- #
step() { printf '  -> %s\n' "$1"; }
ok()   { printf '  [ OK ] %s\n' "$1"; }
info() { printf '  [info] %s\n' "$1"; }
warn() { printf '  [warn] %s\n' "$1" >&2; }
err()  { printf '  [FAIL] %s\n' "$1" >&2; }
die()  { err "$1"; echo; exit 1; }
banner() {
  echo
  echo "---------------------------------------------------------------------------"
  printf '  %s\n' "$1"
  echo "---------------------------------------------------------------------------"
}

# --------------------------------------------------------------------------- #
# Utilities
# --------------------------------------------------------------------------- #
write_text() { # path, content (via stdin)
  mkdir -p "$(dirname "$1")"
  cat > "$1"
}

hash_of() {
  if [ -f "$1" ]; then sha256sum "$1" | awk '{print $1}'; else echo ""; fi
}

# Hash bookkeeping lives in a flat key=value file so both the bash and the
# PowerShell scripts can read it without a JSON parser.
hash_recorded() { # key
  [ -f "$HASHES_PATH" ] || return 1
  sed -n "s/^$1=//p" "$HASHES_PATH" | head -1
}

record_hash() { # key, value
  mkdir -p "$(dirname "$HASHES_PATH")"
  local key="$1" value="$2"
  if [ -f "$HASHES_PATH" ]; then
    sed -i.bak -E "s|^$key=.*$|$key=$value|" "$HASHES_PATH" && rm -f "$HASHES_PATH.bak"
  else
    printf '%s=%s\n' "$key" "$value" > "$HASHES_PATH"
  fi
}

get_env_value() {
  [ -f "$1" ] || return 1
  sed -n "s/^[[:space:]]*$2[[:space:]]*=\(.*\)$/\1/p" "$1" | tail -1 | sed 's/[[:space:]]*$//'
}

set_env_value() { # file, key, value
  local file="$1" key="$2" value="$3"
  if [ ! -f "$file" ]; then mkdir -p "$(dirname "$file")"; : > "$file"; fi
  if grep -qE "^[[:space:]]*$key[[:space:]]*=" "$file"; then
    # portable in-place edit without losing user comments or ordering
    sed -i.bak -E "s|^[[:space:]]*$key[[:space:]]*=.*$|$key=$value|" "$file" && rm -f "$file.bak"
  else
    printf '\n# --- generated by scripts/start.sh ---\n%s=%s\n' "$key" "$value" >> "$file"
  fi
}

import_env() {
  [ -f "$1" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|'#'*) continue ;;
    esac
    key="${line%%=*}"
    value="${line#*=}"
    case "$key" in
      *[!A-Za-z0-9_]*|'') continue ;;
    esac
    export "$key=$value"
  done < "$1"
}

port_pid() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN -t 2>/dev/null | head -1
    return
  fi
  if command -v ss >/dev/null 2>&1; then
    ss -lntp 2>/dev/null | awk -v p=":$port" '$4 ~ p {print $0}' | grep -o 'pid=[0-9]*' | head -1 | cut -d= -f2
    return
  fi
  netstat -an 2>/dev/null | awk -v p="$port" '$2 ~ p && $4 == "LISTEN" {print $7}' | head -1
}

kill_tree() {
  local pid="$1"
  [ "$pid" -gt 0 ] 2>/dev/null || return 0
  pkill -TERM -P "$pid" 2>/dev/null || true
  kill -TERM "$pid" 2>/dev/null || true
  sleep 0.5
  pkill -KILL -P "$pid" 2>/dev/null || true
  kill -KILL "$pid" 2>/dev/null || true
}

tcp_open() { # host, port
  (exec 3<>"/dev/tcp/$1/$2") >/dev/null 2>&1 && exec 3<&- 3>&- && return 0
  return 1
}

wait_http() { # url, timeout_seconds
  local url="$1" timeout="$2" waited=0
  while [ "$waited" -lt "$timeout" ]; do
    if curl -fsS -o /dev/null --max-time 3 "$url" 2>/dev/null; then return 0; fi
    sleep 1
    waited=$((waited + 1))
  done
  return 1
}

wait_tcp() { # host, port, timeout_seconds
  local host="$1" port="$2" timeout="$3" waited=0
  while [ "$waited" -lt "$timeout" ]; do
    if tcp_open "$host" "$port"; then return 0; fi
    sleep 1
    waited=$((waited + 1))
  done
  return 1
}

has_node() { command -v node >/dev/null 2>&1; }
has_npm() { command -v npm >/dev/null 2>&1; }
has_python() { command -v python3 >/dev/null 2>&1 || command -v python >/dev/null 2>&1; }
python_cmd() { if command -v python3 >/dev/null 2>&1; then echo python3; else echo python; fi; }

psql_cmd() {
  if command -v psql >/dev/null 2>&1; then echo psql; return; fi
  for base in /usr/local/opt/libpq/bin /opt/homebrew/opt/libpq/bin /usr/lib/postgresql/*/bin; do
    [ -x "$base/psql" ] && { echo "$base/psql"; return; }
  done
  return 1
}

redis_cli_cmd() { command -v redis-cli >/dev/null 2>&1 && echo redis-cli; return 0; }

postgres_ok() {
  if tcp_open localhost 5432; then return 0; fi
  return 1
}

redis_ok() {
  if command -v redis-cli >/dev/null 2>&1; then
    [ "$(redis-cli -h 127.0.0.1 -p 6379 ping 2>/dev/null | tr -d '\r')" = "PONG" ] && return 0
    return 1
  fi
  tcp_open 127.0.0.1 6379
}

confirm() { # prompt, default y/n
  local prompt="$1" default="$2" answer
  if [ "$default" = "y" ]; then printf '  %s (Y/n) ' "$prompt"; else printf '  %s (y/N) ' "$prompt"; fi
  if [ ! -t 0 ]; then
    echo
    [ "$default" = "y" ]
    return
  fi
  read -r answer
  [ -z "$answer" ] && answer="$default"
  case "$answer" in [yY]|[yY][eE][sS]) return 0 ;; *) return 1 ;; esac
}

# --------------------------------------------------------------------------- #
# Step 1 - prerequisites
# --------------------------------------------------------------------------- #
assert_prerequisites() {
  step "Checking prerequisites"

  if ! has_node; then
    die "Node.js 18+ is required but 'node' was not found. Install Node 18/20/22 from https://nodejs.org"
  fi
  local node_major
  node_major="$(node -v | sed 's/^v//' | cut -d. -f1)"
  if [ "$node_major" -lt 18 ]; then
    die "Node.js $(node -v) is too old. Node.js 18+ is required."
  fi
  if ! has_npm; then die "npm was not found on PATH."; fi
  ok "Node.js $(node -v) + npm $(npm -v)"

  if [ "$EFFECTIVE_MODE" = "docker" ]; then
    command -v docker >/dev/null 2>&1 || die "Docker mode requested but 'docker' is not on PATH. Install Docker Desktop, or run without --mode docker."
    ok "Docker CLI found"
    return
  fi

  has_python || die "Python 3.11+ is required for local mode but no python interpreter was found. Install 3.11+ or use --mode docker."
  local py_ver
  py_ver="$("$(python_cmd)" -c 'import sys;print("%d.%d"%(sys.version_info[0],sys.version_info[1]))')"
  local py_major="${py_ver%%.*}" py_minor="${py_ver##*.}"
  if [ "$py_major" -lt 3 ] || { [ "$py_major" -eq 3 ] && [ "$py_minor" -lt 11 ]; }; then
    die "Python $py_ver is too old. Local mode needs Python 3.11+."
  fi
  ok "Python $py_ver"

  if ! postgres_ok; then
    warn "PostgreSQL is not answering on localhost:5432"
    if command -v brew >/dev/null 2>&1; then
      step "trying to start PostgreSQL via brew services"
      brew services start postgresql@17 >/dev/null 2>&1 || brew services start postgresql@16 >/dev/null 2>&1 || true
      sleep 3
    fi
    postgres_ok || die "PostgreSQL is not reachable on localhost:5432. Start it (brew services start postgresql@17) and re-run."
  fi
  ok "PostgreSQL reachable on localhost:5432"

  if ! redis_ok; then
    warn "Redis is not answering on localhost:6379"
    if command -v brew >/dev/null 2>&1; then
      step "trying to start Redis via brew services"
      brew services start redis >/dev/null 2>&1 || true
      sleep 2
    fi
    redis_ok || die "Redis is not reachable on localhost:6379. Start it (brew services start redis) and re-run."
  fi
  ok "Redis reachable on localhost:6379"
}

# --------------------------------------------------------------------------- #
# Step 2 - LAN IPv4
# --------------------------------------------------------------------------- #
detect_lan_ip() {
  if [ -n "$HOST_IP" ]; then
    info "using --host-ip override: $HOST_IP"
    LAN_IP="$HOST_IP"
    HOST_IP_PINNED=1
    NET_ADAPTER="pinned with --host-ip"
    return
  fi
  HOST_IP_PINNED=0

  # Wait for the network to be up. A machine resuming from sleep, or one that has
  # just joined Wi-Fi, reports no address for a few seconds; without this the
  # script would settle on the 127.0.0.1 fallback and print a QR nobody can scan.
  local waited=0
  while [ "$waited" -lt 20 ]; do
    if detect_lan_ip_once; then return; fi
    sleep 2
    waited=$((waited + 2))
  done

  warn "Could not detect a LAN IPv4 address automatically."
  warn "Falling back to 127.0.0.1 - a phone will NOT reach the demo."
  warn "Re-run with --host-ip 192.168.1.20 if needed."
  LAN_IP="127.0.0.1"
  NET_ADAPTER="none"
}

detect_lan_ip_once() {
  # Ranking is by the metric of the default route the interface holds, lowest
  # wins - the same rule the kernel uses to decide where outbound traffic goes, so
  # it stays correct with a VPN, WSL or VirtualBox adapter layered on top.
  local best="" best_score=-1 best_alias="" best_metric="" count=0
  if command -v ip >/dev/null 2>&1; then
    while read -r ip alias; do
      [ -n "$ip" ] || continue
      case "$alias" in
        *vEthernet*|*VirtualBox*|*VMware*|*docker*|*Docker*|*vbox*|*vmnet*|*br-*|*lo*|*virbr*|*tailscale*) continue ;;
      esac
      case "$ip" in
        127.*|169.254.*) continue ;;
      esac
      count=$((count + 1))

      # Interface state must be UP, not just present.
      local state
      state="$(cat "/sys/class/net/${alias#*/}/operstate" 2>/dev/null || echo unknown)"
      [ "$state" = "down" ] && continue

      local metric=9999
      if command -v ip >/dev/null 2>&1; then
        metric="$(ip route show default dev "${alias#*/}" 2>/dev/null | head -1 |
          sed -n 's/.*metric \([0-9]*\).*/\1/p')"
        [ -z "$metric" ] && metric=9999
      fi

      local score=$((10000 - metric))
      ip route get "$ip" 2>/dev/null | grep -q 'src' && score=$((score + 5000))
      case "$alias" in
        *Wi-Fi*|*WiFi*|*Wireless*|*wlan*|*eth*|*en0*) score=$((score + 200)) ;;
      esac
      if [ "$score" -gt "$best_score" ]; then
        best="$ip"; best_score="$score"; best_alias="$alias"; best_metric="$metric"
      fi
    done < <(ip -o -4 addr show 2>/dev/null | awk '{split($4,a,"/"); print a[1], $2}')
  fi

  if [ -z "$best" ]; then
    best="$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -v '^127\.' | grep -v '^169\.254\.' | head -1)"
  fi

  if [ -z "$best" ]; then
    return 1
  fi

  LAN_IP="$best"
  NET_ADAPTER="${best_alias:-unknown}"
  NET_METRIC="${best_metric:-n/a}"
  NET_GATEWAY="$(ip route show default 2>/dev/null | head -1 | sed -n 's/.*via \([0-9.]*\).*/\1/p')"
  info "detected via interface: ${NET_ADAPTER} (metric ${NET_METRIC}, gateway ${NET_GATEWAY:-none})"
  return 0
}

# --------------------------------------------------------------------------- #
# Step 3 + 4 - env files
# --------------------------------------------------------------------------- #
init_env_files() {
  local api="http://${LAN_IP}:8000"
  local ws="ws://${LAN_IP}:8000"
  # CORS deliberately does not list the LAN IP. It only takes effect when uvicorn
  # restarts, so listing it meant a new address either got refused by the browser
  # or forced a backend restart on every network change. main.py also accepts any
  # loopback/private-LAN origin via CORS_ALLOW_PRIVATE_NETWORK.
  local cors="http://localhost:5173,http://localhost:5174"

  if [ ! -f "$ENV_PATH" ]; then
    if [ -f "$ENV_EXAMPLE" ]; then
      cp "$ENV_EXAMPLE" "$ENV_PATH"
      ok "created .env from .env.example"
    else
      write_text "$ENV_PATH" <<EOF
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=rakshak
DATABASE_URL=postgresql+psycopg2://postgres:postgres@localhost:5432/rakshak
REDIS_URL=redis://localhost:6379/0
JWT_SECRET=rakshak-dev-secret-change-in-production
JWT_ACCESS_MINUTES=30
JWT_REFRESH_DAYS=7
HOTLIST_CONFIRMATION_HOURS=24
DEMO_MODE=true
CORS_ORIGINS=$cors
CORS_ALLOW_PRIVATE_NETWORK=true
STORAGE_BACKEND=local
STORAGE_LOCAL_PATH=./data/uploads
AI_MODEL_PATH=
OCR_MODEL_PATH=
API_BASE_URL=$api
EOF
      warn ".env.example missing - wrote a minimal .env"
    fi
  else
    info ".env already exists - existing values are preserved"
  fi

  # Only these generated keys are rewritten; everything else the user typed stays.
  set_env_value "$ENV_PATH" CORS_ORIGINS "$cors"
  set_env_value "$ENV_PATH" CORS_ALLOW_PRIVATE_NETWORK "true"
  set_env_value "$ENV_PATH" API_BASE_URL "$api"

  # VITE_API_URL / EXPO_PUBLIC_API_URL are written ONLY when an address was given
  # explicitly with --host-ip. Vite inlines VITE_* at build time and Metro inlines
  # EXPO_PUBLIC_* at bundle time, so writing the IP here froze one address into the
  # bundle and the client kept dialling it after the router moved this machine.
  # Each client now derives its host at runtime instead.
  if [ "$HOST_IP_PINNED" = "1" ]; then
    set_env_value "$ENV_PATH" VITE_API_URL "$api"
    set_env_value "$ENV_PATH" VITE_WS_URL "$ws"
    set_env_value "$ENV_PATH" EXPO_PUBLIC_API_URL "$api"
    warn "pinned VITE_API_URL / EXPO_PUBLIC_API_URL to $api (--host-ip); clear them to auto-detect again"
    write_text "$CITIZEN_DIR/.env.local" <<EOF
# Generated by scripts/start.sh - host PINNED with --host-ip.
VITE_API_URL=$api
VITE_WS_URL=$ws
EOF
    cp "$CITIZEN_DIR/.env.local" "$POLICE_DIR/.env.local"
    write_text "$MOBILE_DIR/.env" <<EOF
# Generated by scripts/start.sh. EXPO_PUBLIC_API_URL PINNED with --host-ip.
EXPO_PUBLIC_API_URL=$api
EOF
  else
    set_env_value "$ENV_PATH" VITE_API_URL ""
    set_env_value "$ENV_PATH" VITE_WS_URL ""
    set_env_value "$ENV_PATH" EXPO_PUBLIC_API_URL ""
    ok ".env updated -> $api (client URLs left empty for runtime resolution)"
    write_text "$CITIZEN_DIR/.env.local" <<EOF
# Generated by scripts/start.sh. Left empty on purpose: each app derives the
# backend host from the address in the browser bar at runtime, so it keeps working
# when this machine is given a new IP. Set VITE_API_URL here to pin one.
VITE_API_URL=
VITE_WS_URL=
EOF
    cp "$CITIZEN_DIR/.env.local" "$POLICE_DIR/.env.local"
    write_text "$MOBILE_DIR/.env" <<EOF
# Generated by scripts/start.sh. Left empty on purpose: the app reads the host
# Metro is serving from (Constants.expoConfig.hostUri), so it follows this machine
# to a new network automatically after you rescan the QR in Expo Go.
EXPO_PUBLIC_API_URL=
EOF
  fi
  ok "wrote citizen_web/.env.local, police_dashboard/.env.local, mobile_app/.env"

  import_env "$ENV_PATH"
}

# --------------------------------------------------------------------------- #
# Step 5 - firewall (Linux only, requires sudo; macOS prompts on first bind)
# --------------------------------------------------------------------------- #
init_firewall() {
  [ "$SKIP_FIREWALL" -eq 1 ] && { info "firewall step skipped (--skip-firewall)"; return; }
  [ "$(uname -s)" = "Linux" ] || { info "not Linux - macOS asks for network access on first bind"; return; }
  command -v ufw >/dev/null 2>&1 || { info "ufw not installed - skipping firewall rules"; return; }

  if [ "$(id -u)" -ne 0 ]; then
    warn "not root - firewall rules were NOT added"
    warn "run this once as root to let the phone reach the demo:"
    warn "  sudo ufw allow 8000/tcp && sudo ufw allow 5173/tcp && sudo ufw allow 5174/tcp && sudo ufw allow 8081/tcp"
    return
  fi
  local spec="8000:RAKSHAK-API-8000 5173:RAKSHAK-CITIZEN-5173 5174:RAKSHAK-POLICE-5174 8081:RAKSHAK-EXPO-8081"
  for item in $spec; do
    local port="${item%%:*}" name="${item##*:}"
    ufw allow from 192.168.0.0/16 to any port "$port" proto tcp comment "$name" >/dev/null 2>&1 \
      && ok "ufw opened TCP $port ($name)" || warn "ufw could not open TCP $port"
  done
}

# --------------------------------------------------------------------------- #
# Process tracking (pids.tsv: name <TAB> pid <TAB> label)
# --------------------------------------------------------------------------- #
PIDS_TSV="$STATE_DIR/pids.tsv"

service_pid() { # name
  [ -f "$PIDS_TSV" ] || return 1
  awk -F'\t' -v n="$1" '$1 == n {print $2; exit}' "$PIDS_TSV"
}

service_running() { # name, port
  local pid
  pid="$(service_pid "$1")"
  [ -z "$pid" ] && return 1
  kill -0 "$pid" 2>/dev/null || return 1
  [ -n "$(port_pid "$2")" ]
}

stop_tracked() { # name
  local pid
  pid="$(service_pid "$1")"
  [ -z "$pid" ] && return 0
  if kill -0 "$pid" 2>/dev/null; then
    step "stopping $1 (pid $pid)"
    kill_tree "$pid"
  fi
  if [ -f "$PIDS_TSV" ]; then
    awk -F'\t' -v n="$1" '$1 != n' "$PIDS_TSV" > "$PIDS_TSV.tmp" && mv "$PIDS_TSV.tmp" "$PIDS_TSV"
  fi
}

assert_port_free() { # port, service, allow_reuse
  local port="$1" service="$2" allow_reuse="$3" pid proc
  pid="$(port_pid "$port" | tr -d '[:space:]')"
  [ -z "$pid" ] && return 0
  proc="$(ps -p "$pid" -o comm= 2>/dev/null | head -1)"
  warn "TCP $port is already in use by ${proc:-unknown process} (pid $pid)"
  if [ "$allow_reuse" = "reuse" ]; then
    info "that is the $service started earlier - reusing it"
    return 0
  fi
  if confirm "Stop ${proc:-the process} (pid $pid) and continue?" n; then
    kill_tree "$pid"
    sleep 0.5
    return 0
  fi
  die "TCP $port is held by ${proc:-another process} (pid $pid). Stop it, or use --mode docker."
}

start_process() { # name, label, cwd, command...
  local name="$1" label="$2" cwd="$3"; shift 3
  mkdir -p "$LOG_DIR" "$STATE_DIR"
  local pid
  ( cd "$cwd" && nohup "$@" >"$LOG_DIR/$name.log" 2>"$LOG_DIR/$name.err.log" & echo $! > "$STATE_DIR/$name.pid" )
  pid="$(cat "$STATE_DIR/$name.pid" 2>/dev/null)"
  printf '%s\t%s\t%s\n' "$name" "$pid" "$label" >> "$PIDS_TSV"
  ok "started $label (pid $pid) -> logs/$name.log"
}

# --------------------------------------------------------------------------- #
# Step 6a - local mode
# --------------------------------------------------------------------------- #
init_local_database() {
  if ! psql_cmd >/dev/null; then
    warn "psql not found - skipping the create-database-if-missing check"
    return
  fi
  local psql user pass db
  psql="$(psql_cmd)"
  user="${POSTGRES_USER:-postgres}"
  pass="${POSTGRES_PASSWORD:-postgres}"
  db="${POSTGRES_DB:-rakshak}"

  if PGPASSWORD="$pass" "$psql" -h localhost -U "$user" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$db'" 2>/dev/null | grep -q 1; then
    ok "database '$db' exists"
    return
  fi
  step "creating database '$db'"
  if PGPASSWORD="$pass" "$psql" -h localhost -U "$user" -d postgres -tAc "CREATE DATABASE $db" >/dev/null 2>&1; then
    ok "database '$db' created"
  else
    warn "could not create '$db' (it may already exist)"
  fi
}

hash_recorded() { # key
  [ -f "$HASHES_PATH" ] || return 1
  grep -q "\"$1\":" "$HASHES_PATH" || return 1
  json_get "$HASHES_PATH" "$1" | tr -d '" '
}

record_hash() { # key, value
  mkdir -p "$STATE_DIR"
  local key="$1" value="$2"
  if [ -f "$HASHES_PATH" ]; then
    if grep -q "\"$key\":" "$HASHES_PATH"; then
      sed -i.bak -E "s|\"$key\":[[:space:]]*\"[^\"]*\"|\"$key\": \"$value\"|" "$HASHES_PATH" && rm -f "$HASHES_PATH.bak"
      return
    fi
  fi
  printf '  "%s": "%s"\n}\n' "$key" "$value" >> "$STATE_DIR/hashes.tmp" 2>/dev/null || true
  if [ -f "$STATE_DIR/hashes.tmp" ]; then
    { echo "{"; cat "$STATE_DIR/hashes.tmp"; } > "$HASHES_PATH"
    rm -f "$STATE_DIR/hashes.tmp"
  fi
}

init_python_venv() {
  local python
  python="$(python_cmd)"
  [ "$REBUILD" -eq 1 ] && { warn "-Rebuild: recreating .venv"; rm -rf "$VENV_DIR"; }

  if [ ! -d "$VENV_DIR" ]; then
    step "creating virtual environment at $VENV_DIR"
    "$python" -m venv "$VENV_DIR" || die "could not create the virtual environment at $VENV_DIR"
    ok "virtual environment created"
  fi

  local vpython="$VENV_DIR/bin/python"
  [ -x "$vpython" ] || die "the virtual environment at $VENV_DIR is broken - delete it and re-run"

  local alembic="$VENV_DIR/bin/alembic"
  [ -x "$alembic" ] || die "alembic is not installed in $VENV_DIR - re-run with --rebuild"

  local req_hash prev
  req_hash="$(hash_of "$BACKEND_DIR/requirements.txt")"
  prev="$(hash_recorded backend-requirements)"

  if [ "$REBUILD" -eq 1 ] || [ "$req_hash" != "$prev" ]; then
    step "installing backend dependencies (requirements.txt changed)"
    "$vpython" -m pip install --disable-pip-version-check -q -r "$BACKEND_DIR/requirements.txt" \
      || die "pip install failed - run it by hand in $VENV_DIR to see the error"
    ok "backend dependencies installed"
  else
    info "backend dependencies unchanged - skipping pip install"
  fi
  record_hash backend-requirements "$req_hash"
}

run_alembic() {
  step "applying database migrations (alembic upgrade head)"
  ( cd "$BACKEND_DIR" && "$alembic" upgrade head ) >"$LOG_DIR/alembic.log" 2>&1 \
    || die "alembic upgrade head failed - see logs/alembic.log"
  ok "database schema is up to date"
}

npm_deps() { # dir, key, install (yes/no)
  local dir="$1" key="$2" install="$3"
  local current prev
  current="$(hash_of "$dir/package-lock.json")$(hash_of "$dir/package.json")"
  prev="$(hash_recorded "$key")"
  local leaf; leaf="$(basename "$dir")"

  if [ "$install" = "no" ]; then
    if [ "$REBUILD" -eq 1 ] || [ "$current" != "$prev" ] || [ ! -d "$dir/node_modules" ]; then
      step "$leaf: installing node dependencies"
      ( cd "$dir" && npm ci --no-audit --no-fund >"$LOG_DIR/npm-$leaf.log" 2>&1 ) \
        || die "npm ci failed in $dir - see logs/npm-$leaf.log"
      ok "$leaf: node dependencies installed"
    else
      info "$leaf: dependencies unchanged - skipping npm ci"
    fi
    record_hash "$key" "$current"
    return
  fi
  if [ -d "$dir/node_modules" ] && [ "$current" = "$prev" ] && [ "$REBUILD" -eq 0 ]; then
    info "$leaf: dependencies unchanged - skipping npm ci"
    record_hash "$key" "$current"
    return
  fi
  info "$leaf: dependencies need installing (skipped)"
}

start_backend_local() {
  if service_running backend "$PORT_BACKEND"; then
    ok "backend already running (reusing it)"
    FRESH=0
    return
  fi
  assert_port_free "$PORT_BACKEND" backend prompt
  start_process backend "FastAPI backend" "$BACKEND_DIR" \
    "$VENV_DIR/bin/python" -m uvicorn app.main:app --host 0.0.0.0 --port "$PORT_BACKEND"
}

start_frontend_local() { # name, dir, port, label
  local name="$1" dir="$2" port="$3" label="$4"
  if service_running "$name" "$port"; then
    ok "$label already running (reusing it)"
    FRESH=0
    return
  fi
  assert_port_free "$port" "$name" prompt
  npm_deps "$dir" "${name}-lock" yes
  if [ ! -f "$dir/node_modules/vite/bin/vite.js" ]; then
    warn "$label: vite is not installed yet - skipping"
    return
  fi
  start_process "$name" "$label" "$dir" node node_modules/vite/bin/vite.js --host 0.0.0.0 --port "$port"
}

# --------------------------------------------------------------------------- #
# Step 6b - docker mode
# --------------------------------------------------------------------------- #
start_docker() {
  step "docker compose up -d"
  local args="up -d"
  if [ "$REBUILD" -eq 1 ]; then args="$args --build"; fi

  local current prev
  current="$(hash_of "$REPO_ROOT/docker-compose.yml")$(hash_of "$BACKEND_DIR/Dockerfile")$(hash_of "$BACKEND_DIR/requirements.txt")$(hash_of "$CITIZEN_DIR/Dockerfile")$(hash_of "$CITIZEN_DIR/package.json")$(hash_of "$POLICE_DIR/Dockerfile")$(hash_of "$POLICE_DIR/package.json")"
  prev="$(hash_recorded docker-build)"
  if [ "$REBUILD" -eq 0 ] && [ -n "$prev" ] && [ "$current" != "$prev" ]; then
    info "Dockerfiles / requirements / package.json changed - adding --build"
    args="$args --build"
  fi

  ( cd "$REPO_ROOT" && docker compose $args ) >"$LOG_DIR/docker.log" 2>&1 \
    || die "docker compose up failed - see logs/docker.log"
  record_hash docker-build "$current"
  ok "containers started"

  step "waiting for containers to report healthy"
  ( cd "$REPO_ROOT" && docker compose ps ) || true
}

# --------------------------------------------------------------------------- #
# Step 8 - seeding
# --------------------------------------------------------------------------- #
run_seeding() {
  local seed_hash marker
  seed_hash="$(hash_of "$SCRIPT_DIR/seed_demo.py")"
  marker=""
  [ -f "$SEED_MARKER" ] && marker="$(cat "$SEED_MARKER")"

  if [ "$FORCE_SEED" -eq 0 ] && [ "$REBUILD" -eq 0 ] && [ "$seed_hash" = "$marker" ] && [ -n "$seed_hash" ]; then
    ok "demo data already seeded (skipping - idempotent, runs once)"
    info "to re-seed: ./scripts/start.sh --reset (or --force-seed)"
    return
  fi

  step "seeding demo users and demo data (idempotent)"
  [ -f "$SCRIPT_DIR/seed_demo.py" ] || {
    warn "scripts/seed_demo.py not found - demo users are still seeded by the backend on startup"
    return
  }

  if [ "$EFFECTIVE_MODE" = "docker" ]; then
    ( cd "$REPO_ROOT" && docker compose exec -T backend python scripts/seed_demo.py ) >"$LOG_DIR/seed_demo.log" 2>&1 || \
      warn "seeding inside the container failed - see logs/seed_demo.log"
  else
    ( cd "$REPO_ROOT" && "$VENV_DIR/bin/python" scripts/seed_demo.py ) >"$LOG_DIR/seed_demo.log" 2>&1 || \
      warn "seeding failed - see logs/seed_demo.log"
  fi
  ok "demo data seeded (see logs/seed_demo.log)"
  echo -n "$seed_hash" > "$SEED_MARKER"
}

# --------------------------------------------------------------------------- #
# Step 9 - Expo (always on the host)
# --------------------------------------------------------------------------- #
# Keep the native modules on the SDK the installed `expo` expects, then report
# doctor failures only - a wall of passing checks is noise in a start script.
sync_expo_sdk() {
  local cli="$MOBILE_DIR/node_modules/expo/bin/cli"
  [ -f "$cli" ] || return 0

  local out
  out="$( cd "$MOBILE_DIR" && node "$cli" install --check 2>&1 || true )"
  if printf '%s' "$out" | grep -qE 'should be updated|expected version'; then
    step "mobile_app: native modules do not match this SDK - running expo install --fix"
    ( cd "$MOBILE_DIR" && node "$cli" install --fix >"$LOG_DIR/npm-mobile_app.log" 2>&1 ) || true
    ok "mobile_app: native modules realigned to the installed Expo SDK"
  fi

  # SDK 58 removed `expo doctor`; the standalone binary is the only route.
  local doctor
  doctor="$MOBILE_DIR/node_modules/.bin/expo-doctor"
  if [ ! -x "$doctor" ]; then
    warn "mobile_app: expo-doctor is not installed - run: npx expo install expo-doctor -- --save-dev"
    return 0
  fi
  out="$( cd "$MOBILE_DIR" && "$doctor" 2>&1 || true )"
  local line; line="$(printf '%s' "$out" | grep -Eo '[0-9]+/[0-9]+ checks passed' | head -n1)"
  if [ -n "$line" ]; then
    local passed total
    passed="${line%%/*}"
    total="$(printf '%s' "$line" | cut -d/ -f2 | cut -d' ' -f1)"
    if [ "$passed" = "$total" ]; then
      ok "mobile_app: expo-doctor $line"
    else
      warn "mobile_app: expo-doctor $line"
      printf '%s' "$out" | grep -E '^[[:space:]]*(✖|Advice:|Install |Missing |npx expo )' | sed 's/^/    /' || true
    fi
  else
    warn "mobile_app: expo-doctor produced no summary line"
  fi
}

# authorized | unauthorized | none | no-adb. Never fails: no phone is normal.
phone_state() {
  local adb; adb="$(command -v adb 2>/dev/null || true)"
  if [ -z "$adb" ] && [ -x "$STATE_DIR/platform-tools/adb" ]; then
    adb="$STATE_DIR/platform-tools/adb"
  fi
  if [ -z "$adb" ]; then echo "no-adb"; return; fi

  local out; out="$("$adb" devices 2>/dev/null || true)"
  printf '%s' "$out" | grep -q 'unauthorized' && { echo "unauthorized"; return; }
  printf '%s' "$out" | grep -qE '^device[[:space:]]' && { echo "authorized"; return; }
  echo "none"
}

start_expo() {
  if [ "$NO_MOBILE" -eq 1 ]; then info "mobile app skipped (--no-mobile)"; return; fi

  # Metro publishes the address it started with, so after the machine changes
  # network it is the one process that is genuinely wrong. A reused Metro keeps
  # advertising the old address: the phone cannot attach ("No apps connected") and
  # the printed QR encodes an IP that no longer exists. So an IP change always
  # restarts it, while an unchanged one still reuses it.
  local prev_ip=""
  if [ -f "$STATE_PATH" ]; then
    prev_ip="$(sed -n 's/.*"ip"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$STATE_PATH" | head -1)"
  fi

  if service_running expo "$PORT_EXPO"; then
    if [ -n "$prev_ip" ] && [ "$prev_ip" != "$LAN_IP" ]; then
      warn "LAN IP changed $prev_ip -> $LAN_IP: restarting Metro so it advertises the new address"
      stop_tracked expo || true
      sleep 2
    else
      ok "Expo Metro already running (reusing it)"
      FRESH=0
      PHONE_STATE="$(phone_state)"
      return
    fi
  fi

  npm_deps "$MOBILE_DIR" mobile-lock yes
  sync_expo_sdk
  assert_port_free "$PORT_EXPO" expo prompt

  # --clear when anything that shapes the bundle changed since the last run, and
  # also when the network moved: the advertised host is part of what a stale
  # Metro would keep serving.
  local cfg prev
  cfg="$(hash_of "$MOBILE_DIR/package.json")$(hash_of "$MOBILE_DIR/app.json")$(hash_of "$MOBILE_DIR/.env")"
  prev="$(hash_recorded expo-config)"
  local args="start --lan"
  if [ "$REBUILD" -eq 1 ] || [ "$cfg" != "$prev" ] || { [ -n "$prev_ip" ] && [ "$prev_ip" != "$LAN_IP" ]; }; then
    args="$args --clear"
    info "mobile_app: config or network changed since last run - starting Metro with --clear"
  fi
  record_hash expo-config "$cfg"

  # A USB-attached phone lets the CLI install/open the matching Expo Go on it.
  PHONE_STATE="$(phone_state)"
  case "$PHONE_STATE" in
    authorized)
      ok "phone detected over USB - Expo CLI will open the app on it"
      args="$args --android"
      ;;
    unauthorized)
      warn 'phone seen but not authorised - tap "Allow USB debugging" on it, then re-run start.sh'
      ;;
  esac

  if [ -f "$MOBILE_DIR/node_modules/expo/bin/cli" ]; then
    # Pin the address Metro advertises. Left unset, Expo picks an interface itself
    # and with a VPN or several virtual adapters present that is regularly the
    # wrong one - the QR then points somewhere the phone cannot reach.
    REACT_NATIVE_PACKAGER_HOSTNAME="$LAN_IP" \
      start_process expo "Expo Metro" "$MOBILE_DIR" node node_modules/expo/bin/cli $args
    ok "Expo Metro starting on $LAN_IP"
    echo "  Expo URL   : exp://${LAN_IP}:${PORT_EXPO}"
    info '"No apps connected" means the phone still points at the old address - rescan the QR.'
  else
    warn "expo CLI not installed - run: cd mobile_app && npm install && npx expo start --lan"
  fi
}

# --------------------------------------------------------------------------- #
# Step 7 + 10 - readiness and summary
# --------------------------------------------------------------------------- #
results_store=""

record_result() { results_store="${results_store}$1|${2}|${3}\n"; }

wait_readiness() {
  local backend_ok=0 citizen_ok=0 police_ok=0 expo_ok=0 pg_ok=0 redis_ok_final=0

  step "waiting for the backend (60s)"
  if wait_http "http://127.0.0.1:$PORT_BACKEND/api/v1/healthz" 60 || wait_http "http://127.0.0.1:$PORT_BACKEND/health" 5; then
    backend_ok=1; ok "Backend API"; else err "Backend API  (logs/backend.err.log)"; fi
  record_result "Backend API" "$backend_ok" "http://${LAN_IP}:8000/docs"

  if wait_http "http://127.0.0.1:$PORT_CITIZEN/" 30; then citizen_ok=1; ok "Citizen web"; else err "Citizen web  (logs/citizen.err.log)"; fi
  record_result "Citizen web" "$citizen_ok" "http://${LAN_IP}:5173"

  if wait_http "http://127.0.0.1:$PORT_POLICE/" 30; then police_ok=1; ok "Police dashboard"; else err "Police dashboard  (logs/police.err.log)"; fi
  record_result "Police dashboard" "$police_ok" "http://${LAN_IP}:5174"

  if [ "$NO_MOBILE" -eq 0 ]; then
    if wait_http "http://127.0.0.1:$PORT_EXPO/status" 45; then expo_ok=1; ok "Expo Metro (mobile)"; else err "Expo Metro  (logs/expo.err.log)"; fi
  fi
  record_result "Expo Metro" "$expo_ok" "http://${LAN_IP}:8081"

  if redis_ok; then redis_ok_final=1; ok "Redis"; else err "Redis"; fi
  record_result "Redis" "$redis_ok_final" "localhost:6379"

  if postgres_ok; then pg_ok=1; ok "PostgreSQL"; else err "PostgreSQL"; fi
  record_result "PostgreSQL" "$pg_ok" "localhost:5432"

  [ "$backend_ok" -eq 1 ] || return 1
  return 0
}

print_summary() {
  echo
  echo "---------------------------------------------------------------------------"
  printf '  %-20s %-34s %-24s %s\n' "SERVICE" "URL ON THIS NETWORK" "LOCAL" "STATUS"
  echo "  ------------------------------------------------------------------------------"
  printf '  %-20s %-34s %-24s %s\n' "Backend API" "http://${LAN_IP}:8000/docs" "http://localhost:8000/docs" "PASS"
  printf '  %-20s %-34s %-24s %s\n' "Citizen web" "http://${LAN_IP}:5173" "http://localhost:5173" "PASS"
  printf '  %-20s %-34s %-24s %s\n' "Police dashboard" "http://${LAN_IP}:5174" "http://localhost:5174" "PASS"
  if [ "$NO_MOBILE" -eq 1 ]; then
    printf '  %-20s %-34s %-24s %s\n' "Expo Metro" "-" "-" "SKIPPED"
  else
    printf '  %-20s %-34s %-24s %s\n' "Expo Metro" "http://${LAN_IP}:8081" "http://localhost:8081" "PASS"
  fi
  printf '  %-20s %-34s %-24s %s\n' "PostgreSQL" "localhost:5432" "localhost:5432" "PASS"
  printf '  %-20s %-34s %-24s %s\n' "Redis" "localhost:6379" "localhost:6379" "PASS"
  case "$PHONE_STATE" in
    authorized)   phone_status="CONNECTED" ;;
    unauthorized) phone_status="TAP ALLOW" ;;
    no-adb)       phone_status="NO ADB" ;;
    not-checked)  phone_status="SKIPPED" ;;
    *)            phone_status="NOT PLUGGED" ;;
  esac
  printf '  %-20s %-34s %-24s %s\n' "Phone over USB" "-" "-" "$phone_status"
  echo "---------------------------------------------------------------------------"

  echo
  echo "  Mobile app"
  local sdk="unknown"
  if [ -f "$MOBILE_DIR/package.json" ]; then
    sdk="$(grep -o '"expo"[[:space:]]*:[[:space:]]*"[^"]*"' "$MOBILE_DIR/package.json" | head -n1 | cut -d'"' -f4)"
  fi
  echo "    Expo SDK   : ${sdk:-unknown}"
  echo "    Expo URL   : exp://${LAN_IP}:8081"
  api_url="$(grep -m1 '^EXPO_PUBLIC_API_URL=' "$MOBILE_DIR/.env" 2>/dev/null | cut -d= -f2- || true)"
  echo "    API target : ${api_url:-not set}"
  if [ "$NO_MOBILE" -eq 0 ] && [ "$PHONE_STATE" != "authorized" ]; then
    echo
    echo "  To install Expo Go SDK 58: plug the phone in by USB, enable USB debugging,"
    echo "  tap Allow, then run start.sh again (only needed once)."
  fi

  echo
  echo "  Swagger API docs : http://${LAN_IP}:8000/docs"
  echo "  Backend health   : http://${LAN_IP}:8000/health"
  echo
  echo "  Demo logins"
  echo "    citizen    citizen@example.com    Citizen@123"
  echo "    volunteer  volunteer@example.com  Volunteer@123"
  echo "    cop        cop@example.com        Police@123"
  echo "    admin      admin@example.com      Admin@123"
  echo
  echo "  On your phone: same Wi-Fi as this PC, open Expo Go / the dev client and scan the QR"
  echo
  echo "  Logs    : logs/<service>.log"
  echo "  Stop    : ./stop.sh"
  echo
}

# --------------------------------------------------------------------------- #
# Reset
# --------------------------------------------------------------------------- #
do_reset() {
  warn "This stops every service AND deletes the demo data."
  if [ "$EFFECTIVE_MODE" = "docker" ]; then
    warn "  docker volumes (postgres data) will be wiped"
  else
    warn "  the PostgreSQL database '${POSTGRES_DB:-rakshak}' will be dropped and recreated"
  fi
  confirm "Are you sure?" n || { info "reset cancelled"; return; }

  step "stopping everything"
  "$SCRIPT_DIR/stop.sh" --mode "$EFFECTIVE_MODE" >/dev/null 2>&1 || true

  if [ "$EFFECTIVE_MODE" = "docker" ]; then
    step "removing containers and volumes"
    ( cd "$REPO_ROOT" && docker compose down -v >/dev/null 2>&1 ) || warn "docker compose down -v failed"
    ok "docker volumes removed"
    rm -f "$SEED_MARKER"
    return
  fi

  local psql user pass db
  if psql_cmd >/dev/null; then
    psql="$(psql_cmd)"
    user="${POSTGRES_USER:-postgres}"; pass="${POSTGRES_PASSWORD:-postgres}"; db="${POSTGRES_DB:-rakshak}"
    step "dropping database '$db'"
    PGPASSWORD="$pass" "$psql" -h localhost -U "$user" -d postgres -tAc "DROP DATABASE IF EXISTS $db WITH (FORCE)" >/dev/null 2>&1 || true
    PGPASSWORD="$pass" "$psql" -h localhost -U "$user" -d postgres -tAc "CREATE DATABASE $db" >/dev/null 2>&1 || warn "could not recreate '$db'"
    ok "database '$db' dropped and recreated"
  else
    warn "psql not found - drop the database manually: DROP DATABASE ${POSTGRES_DB:-rakshak} WITH (FORCE); CREATE DATABASE ${POSTGRES_DB:-rakshak};"
  fi

  for name in backend citizen police expo; do stop_tracked "$name"; done
  for port in "$PORT_BACKEND" "$PORT_CITIZEN" "$PORT_POLICE" "$PORT_EXPO"; do
    pid="$(port_pid "$port" | tr -d '[:space:]')"
    [ -n "$pid" ] && kill_tree "$pid"
  done
  for name in backend citizen police expo; do stop_tracked "$name"; done
  for port in "$PORT_BACKEND" "$PORT_CITIZEN" "$PORT_POLICE" "$PORT_EXPO"; do
    pid="$(port_pid "$port" | tr -d '[:space:]')"
    [ -n "$pid" ] && kill_tree "$pid"
  done
  rm -f "$SEED_MARKER"
  ok "reset finished - the services will start again in a moment"
}

# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
trap 'warn "interrupted"; if [ "$EFFECTIVE_MODE" = "local" ]; then for n in backend citizen police expo; do stop_tracked "$n"; done; fi; exit 130' INT TERM

banner "RAKSHAK - one command startup"
info "repository : $REPO_ROOT"

mkdir -p "$STATE_DIR" "$LOG_DIR"

detect_lan_ip
step "LAN IP    : $LAN_IP"

# Remember the address, and say so when it moved since the previous run. This is
# what makes a second run after a network change behave differently from the
# first: Metro is restarted because the URL it advertises is now wrong.
prev_ip=""
if [ -f "$STATE_PATH" ]; then
  # Read without a JSON parser: the file is written by this function and has one
  # flat level under "state", so a single anchored match is exact. (json_get does
  # not exist here, which is why hash_recorded has always silently returned empty.)
  prev_ip="$(sed -n 's/.*"ip"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$STATE_PATH" | head -1)"
fi
write_text "$STATE_PATH" <<EOF
{
  "state": {
    "ip": "$LAN_IP",
    "adapter": "$NET_ADAPTER",
    "gateway": "$NET_GATEWAY",
    "updatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  }
}
EOF
if [ -n "$prev_ip" ] && [ "$prev_ip" != "$LAN_IP" ]; then
  warn "network changed since the last run: $prev_ip -> $LAN_IP"
  info "Metro will restart so it advertises the new address; web apps and backend keep running"
fi

# mode selection
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  docker_ready=1
else
  docker_ready=0
fi

case "$MODE" in
  auto)
    if [ "$docker_ready" -eq 1 ]; then EFFECTIVE_MODE="docker"; else
      EFFECTIVE_MODE="local"
      if command -v docker >/dev/null 2>&1; then
        warn "the Docker CLI is installed but the daemon is not running - falling back to local mode"
        warn "start Docker Desktop and re-run if you prefer containers"
      fi
    fi
    ;;
  docker)
    if [ "$docker_ready" -eq 0 ]; then
      warn "the Docker daemon is not running - falling back to local mode"
      EFFECTIVE_MODE="local"
    else
      EFFECTIVE_MODE="docker"
    fi
    ;;
  *) EFFECTIVE_MODE="local" ;;
esac

step "mode      : $(printf '%s' "$EFFECTIVE_MODE" | tr '[:lower:]' '[:upper:]')$( [ "$REBUILD" -eq 1 ] && echo ' (rebuild)' )"

# Remember the mode so stop.sh knows what to tear down without asking.
echo -n "$EFFECTIVE_MODE" > "$STATE_DIR/mode"

assert_prerequisites
init_env_files
init_firewall
[ "$RESET" -eq 1 ] && do_reset

if [ "$EFFECTIVE_MODE" = "docker" ]; then
  start_docker
else
  init_local_database
  init_python_venv
  run_alembic
  start_backend_local
  start_frontend_local citizen "$CITIZEN_DIR" "$PORT_CITIZEN" "citizen web"
  start_frontend_local police "$POLICE_DIR" "$PORT_POLICE" "police dashboard"
fi

banner "Waiting for services"
exit_code=0
wait_readiness || exit_code=1

[ "$exit_code" -eq 0 ] && run_seeding || warn "backend is not healthy - skipping demo seeding"

start_expo

print_summary

echo "  Stop    : ./stop.sh" >&2
exit "$exit_code"